# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_group_title', models.CharField(max_length=50, unique=True)),
                ('role_group_alias', models.CharField(max_length=60, unique=True)),
                ('role_group_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('role_group_enabled', models.BooleanField(default=1)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'role_group',
            },
        ),
        migrations.CreateModel(
            name='RoleSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_supplier_title', models.CharField(max_length=150)),
                ('role_supplier_address', models.CharField(max_length=200)),
                ('role_supplier_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('role_supplier_enabled', models.BooleanField(default=1)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'role_supplier',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_user_username', models.CharField(max_length=50, unique=True)),
                ('role_user_password', models.CharField(max_length=300)),
                ('role_user_email', models.CharField(max_length=60, unique=True)),
                ('role_user_firstname', models.CharField(max_length=60, unique=True)),
                ('role_user_lastname', models.CharField(max_length=60, unique=True)),
                ('role_user_address', models.CharField(max_length=60, unique=True)),
                ('role_user_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('role_user_enabled', models.BooleanField(default=1)),
                ('role_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user_group', to='role.RoleGroup')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'role_user',
            },
        ),
        migrations.AddField(
            model_name='rolesupplier',
            name='role_supplier_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_supplier_user_key', to='role.RoleUser'),
        ),
        migrations.AddIndex(
            model_name='rolesupplier',
            index=models.Index(fields=['role_supplier_title', 'role_supplier_address'], name='role_suppli_role_su_fb0188_idx'),
        ),
    ]
