# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_user_token_uuid1', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('role_user_token_uuid2', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('role_user_token_start_date', models.DateTimeField(auto_now_add=True)),
                ('role_user_token_end_date', models.DateTimeField()),
                ('role_user_token_ip', models.CharField(max_length=16)),
                ('role_user_token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user_token_user_key', to='role.RoleUser')),
            ],
            options={
                'db_table': 'role_user_token',
            },
        ),
    ]
