# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_roleusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='role_user_address',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
