# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pill.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_drug_title', models.CharField(max_length=100)),
                ('main_drug_article', models.CharField(max_length=100, unique=True)),
                ('main_drug_description', models.TextField(blank=True, null=True)),
                ('main_drug_prescription', models.BooleanField(default=0)),
                ('main_drug_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'main_drug',
            },
        ),
        migrations.CreateModel(
            name='ResellerDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_drug_title', models.CharField(max_length=100)),
                ('reseller_drug_alias_article', models.CharField(max_length=100, unique=True)),
                ('reseller_drug_description', models.TextField(blank=True, null=True)),
                ('reseller_drug_price', models.FloatField()),
                ('reseller_drug_available', models.BooleanField(default=0)),
                ('reseller_drug_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('reseller_drug_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_drug_dealer_key', to='role.RoleSupplier')),
                ('reseller_drug_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_drug_main_key', to='pill.MainDrug')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'reseller_drug',
            },
        ),
        migrations.CreateModel(
            name='ResellerDrugImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_drug_image', models.ImageField(upload_to=pill.models.get_upload_path)),
                ('reseller_drug_image_created', models.DateTimeField(auto_now_add=True)),
                ('reseller_drug_image_main', models.BooleanField(default=0)),
                ('main_drug_image_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('reseller_drug_image_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_drug_image_drug_key', to='pill.ResellerDrug')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'reseller_drug_image',
            },
        ),
        migrations.AddIndex(
            model_name='maindrug',
            index=models.Index(fields=['main_drug_title', 'main_drug_article', 'main_drug_description'], name='main_drug_main_dr_4c72f6_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerdrug',
            index=models.Index(fields=['reseller_drug_title', 'reseller_drug_alias_article', 'reseller_drug_description', 'reseller_drug_price'], name='reseller_dr_reselle_caa9a0_idx'),
        ),
    ]
